version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Installing dependencies..."
      - pip install requests
      - echo "Running sports data lake script..."
      - python setup_sports_data_lake.py
